apiVersion: v1
kind: Service
metadata:
    name: "kubernetestest-0948"
    labels:
        app: "kubernetestest-0948"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubernetestest-0948"